//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace housing.estate.spider.test {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("housing.estate.spider.test.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;【天通西苑三区房价|昌平天通西苑三区】-北京小区-链家在线&lt;/title&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;链家在线-小区房价频道为您提供昌平天通苑附近天通西苑三区房价信息,天通西苑三区出售,转让信息,同时,我们还提供天通西苑三区出租信息供您选择.让您及时获得天通西苑三区房源出售、转让、出租信息&quot; /&gt;
        ///&lt;meta name=&quot;keywords&quot; content=&quot;天通西苑三区,北京二手房,昌平二手房,天通西苑三区房价&quot; /&gt;
        ///&lt;link type=&quot;text/css&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string home_link_estate_detail {
            get {
                return ResourceManager.GetString("home_link_estate_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        /// &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        /// &lt;head&gt;
        /// &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        /// &lt;title&gt;【北京小区房价|北京小区信息】-北京小区-链家在线&lt;/title&gt;
        /// &lt;meta name=&quot;description&quot; content=&quot;链家在线北京小区信息频道,为您提供最新最真实的北京小区房价,您可以了解到北京小区信息价格,北京小区信息信息,是中国最专业的北京小区信息网,720度拍摄的北京小区内详图,加上最智能的北京出小区信息源推荐,让您小区信息只需homelink.com.cn一下轻松搞定&quot; /&gt;
        /// &lt;meta name=&quot;keywords&quot; content=&quot;北京小区房价,北京小区信息&quot; / [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string home_link_page_content {
            get {
                return ResourceManager.GetString("home_link_page_content", resourceCulture);
            }
        }
    }
}
